language: python
install: pip install pylint coverage coveralls
python:
  - "3.7"

script:
  - pylint `find . -name '*.py'`
  - coverage run -m unittest discover tests 

after_success:
  - coveralls

branches:
  only:
  - master
